### ISSUE TITLE
Training time and Size of the dataset

### ISSUE THREAD

**Issue by njan-creative** [BCV-Uniandes/SIMBA#2]
Can you please let me  know the training time and the size of the dataset used ?

**Comment by cigonzalez** [comment]
The total training time is 11 hours using a  an NVIDIA TITAN-X Pascal GPU for 150 epochs. The dataset is composed of 6,288
images divided into 3 sets: 5,492 for training, 716 for validation and 80 for testing. In this [paper](https://biomedicalcomputervision.uniandes.edu.co/images/papers/Hand_Pose_Estimation_for_Pediatric_Bone_Age_Assessment.pdf) you could find more information about the dataset we used.
